baseURL = '/'
title = 'accessible.tips'

DefaultContentLanguage = "en"
languageCode = 'en-us'
timeZone = 'UTC'

enableEmoji = true
enableRobotsTXT = true
enableGitInfo = true
rssLimit = 25

ignoreFiles = [ '.gitignore', '.gitkeep' ]

theme = ['hugo-xmin']

footnotereturnlinkcontents = '↩'

uglyURLs = false
[permalinks]
  tips = '/tips/:slug/'
  posts = '/posts/:year-:month-:day-:slug/'
  tags = '/tags/:title/'

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

[imaging]
  [imaging.exif]
    disableDate = false
    disableLatLong = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlilght]
    codeFences = false

[outputs]
    home = ["HTML", "RSS", "JSON"]

[params]
  description = 'A collection of accessibility tips and tricks'
  footer = '&copy; {Year}'

[menu]
[[menu.main]]
  identifier = 'search'
  name = 'Search'
  url = '/search/'
  weight = 10
[[menu.main]]
  identifier = 'categories'
  name = 'Categories'
  url = '/categories/'
  weight = 20
[[menu.main]]
  identifier = 'tips'
  name = 'Tips'
  url = '/tips/'
  weight = 30
[[menu.main]]
  identifier = 'faq'
  name = 'FAQ'
  url = '/faq/'
  weight = 40
[[menu.main]]
  identifier = 'posts'
  name = 'News'
  url = '/posts/'
  weight = 50
[[menu.main]]
  identifier = 'rss'
  name = 'RSS'
  url = 'index.xml'
  weight = 60

#[[menu.main]]
#  identifier = 'tags'
#  name = 'Tags'
#  url = '/tags/'
#  weight = 30